commands.go /// handleMove i dont know the cause of the error but i just copied the name from a different part of the code base/// error now gone// cmd/commands.go:193:3: undefined: handleMove // yay🧙